FROM postgres:12.2-alpine

ENV WALG_VERSION=v0.2.15

ENV _build_deps="go wget cmake git build-base bash lz4"

RUN set -ex  \
     && apk add --no-cache $_build_deps

RUN cd /tmp \
     && wget -qO - https://github.com/google/brotli/archive/v1.0.7.tar.gz | tar xz -f '-' \
     && cd brotli* \
     && mkdir out \
     && cd out \
     && ../configure-cmake --disable-debug \
     && make \
     && make install

RUN git clone https://github.com/wal-g/wal-g/  $GOPATH/src/wal-g \
     && cd $GOPATH/src/wal-g/ \
     && git checkout $WALG_VERSION \
     && make install \
     && make deps \
     && make pg_build \
     && make link_brotli \
     && install main/pg/wal-g / \
     && /wal-g --help

RUN mkdir -p /etc/postgresql/ \
    && cp /usr/local/share/postgresql/postgresql.conf.sample /etc/postgresql/postgresql.conf \
    && sed -ri "s/^#archive_mode = off/archive_mode = on/" /etc/postgresql/postgresql.conf \
    && sed -ri "s/^#archive_command = ''/archive_command = '\/wal-g wal-push %p'/" /etc/postgresql/postgresql.conf \
    && sed -ri "s/^#restore_command = ''/restore_command = '\/wal-g wal-fetch %f %p'/" /etc/postgresql/postgresql.conf

ENV PGHOST=/var/run/postgresql

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]